In [2]:
import numpy as np

lista = np.arange(1, 10)



In [4]:
np.sum(lista)

45

In [5]:
np.prod(lista)

362880

In [6]:
np.cumsum(lista)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [9]:
lista1 = np.array([1,2,3])
lista2 = np.array([4,5,6])

lista3 = np.add(lista1, lista2)

lista3

array([5, 7, 9])

Para multiplicar duas matrizes NumPy, podemos usar a função dot() ou o operador @. Ambos os métodos executam a multiplicação matricial. É importante lembrar que, para que a multiplicação de matrizes possa ser executada, o número de colunas da primeira matriz deve ser igual ao número de linhas da segunda matriz.

Há várias formas de multiplicar elementos de matrizes NumPy. A função dot() é um método bastante utilizado.

In [10]:
# Cria duas matrizes
lista4 = np.array([[1, 2], [3, 4]])
lista5 = np.array([[5, 6], [0, 7]])

In [11]:
lista6 = np.dot(lista4, lista5)

lista6

array([[ 5, 20],
       [15, 46]])