## Iniciando o Numpy

In [1]:
# Importando o numpy
import numpy as np

In [19]:
# Criando uma lista com o numpy
array = np.array([1,2,3,4,5,6,7,8])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz3 = np.array([[[1],[2]], [[1], [2]], [[1], [2]]])

In [12]:
print(array, end='\n\n')
print(matriz, end='\n\n')
print(matriz3, end='\n\n')
# Um objeto ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
print(type(array))
print(type(matriz))
print(type(matriz3))


[1 2 3 4 5 6 7 8]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
# verificando o formato de dado: Repare que só tem uma única dimensão, ou seja, é um vetor
print(array.shape)
print(matriz.shape)
print(matriz3.shape)

(8,)
(3, 3)
(3, 2, 1)


## Indexação Numpy

In [21]:
print(array)

[1 2 3 4 5 6 7 8]


In [22]:
# Vamos pegar um valor especifico
print(array[4])

5


In [23]:
# Vamos pegar um intervalo
print(array[1:4])
print(array[1:4+1])

[2 3 4]
[2 3 4 5]


In [24]:
# Criando uma lista de indices
indices = [1, 4, 5, 0]
print(array[indices])

[2 5 6 1]


In [26]:
array2 = array
# Criando uma mascara booleana para filtrar os elementos pares
mask = (array2 % 2 == 0)
print(mask)
print(array2[mask])

[False  True False  True False  True False  True]
[2 4 6 8]


In [27]:
# Mudando um valor especifico
array2[0] = 999
print(array2)

[999   2   3   4   5   6   7   8]


### Atenção: Ao contrário de listas convencionais Python, o numpy não permite que eu mescle diferentes tipos de dados em um único array.

# FUNÇÕES NUMPY

In [1]:
import numpy as np

In [2]:
lista_funcoes = np.array([10, 32, 2, 10])

In [3]:
for i in lista_funcoes:
    print(i)

10
32
2
10


In [4]:
# Soma acumulada: 
lista_funcoes.cumsum()

array([10, 42, 44, 54], dtype=int32)

In [5]:
# Produto acumulado
lista_funcoes.cumprod()

array([  10,  320,  640, 6400], dtype=int32)

In [8]:
# A função arange cria um array Numpy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = np.arange(0, 50, 2)

arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [9]:
np.shape(arr3)

(25,)

In [12]:
# Vamos verificar o tipo de dado nesse array:
print(arr3.dtype)

int32


Repare as notações acima.

Quando mexo com metodos
numpy.metodo(lista)
Quando mexo com atributos
lista.atributo

In [14]:
# Criando uma lista com zeros
arr4 = np.zeros(10)

arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = np.eye(10)

arr5

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
# Posso produzir a minha própria matriz diagonal

arr6 = np.diag(np.array(['d', 'a', 'n', 'i', 'e', 'l']))

arr6

array([['d', '', '', '', '', ''],
       ['', 'a', '', '', '', ''],
       ['', '', 'n', '', '', ''],
       ['', '', '', 'i', '', ''],
       ['', '', '', '', 'e', ''],
       ['', '', '', '', '', 'l']], dtype='<U1')

In [21]:
# Posso criar um array com falores booleanos

arr7 = np.array([True, False, True, False, True, True])

arr7

array([ True, False,  True, False,  True,  True])

In [22]:
arr8 = np.array(['d', 'a', 'n', 'i', 'e', 'l'])

arr8

array(['d', 'a', 'n', 'i', 'e', 'l'], dtype='<U1')

In [23]:
# Explicação no docs
print(np.logspace(20, 33))

[1.00000000e+20 1.84206997e+20 3.39322177e+20 6.25055193e+20
 1.15139540e+21 2.12095089e+21 3.90693994e+21 7.19685673e+21
 1.32571137e+22 2.44205309e+22 4.49843267e+22 8.28642773e+22
 1.52641797e+23 2.81176870e+23 5.17947468e+23 9.54095476e+23
 1.75751062e+24 3.23745754e+24 5.96362332e+24 1.09854114e+25
 2.02358965e+25 3.72759372e+25 6.86648845e+25 1.26485522e+26
 2.32995181e+26 4.29193426e+26 7.90604321e+26 1.45634848e+27
 2.68269580e+27 4.94171336e+27 9.10298178e+27 1.67683294e+28
 3.08884360e+28 5.68986603e+28 1.04811313e+29 1.93069773e+29
 3.55648031e+29 6.55128557e+29 1.20679264e+30 2.22299648e+30
 4.09491506e+30 7.54312006e+30 1.38949549e+31 2.55954792e+31
 4.71486636e+31 8.68511374e+31 1.59985872e+32 2.94705170e+32
 5.42867544e+32 1.00000000e+33]


In [24]:
print(np.linspace(20, 33))

[20.         20.26530612 20.53061224 20.79591837 21.06122449 21.32653061
 21.59183673 21.85714286 22.12244898 22.3877551  22.65306122 22.91836735
 23.18367347 23.44897959 23.71428571 23.97959184 24.24489796 24.51020408
 24.7755102  25.04081633 25.30612245 25.57142857 25.83673469 26.10204082
 26.36734694 26.63265306 26.89795918 27.16326531 27.42857143 27.69387755
 27.95918367 28.2244898  28.48979592 28.75510204 29.02040816 29.28571429
 29.55102041 29.81632653 30.08163265 30.34693878 30.6122449  30.87755102
 31.14285714 31.40816327 31.67346939 31.93877551 32.20408163 32.46938776
 32.73469388 33.        ]


# Manipulando Matrizes

In [3]:
import numpy as np

matriz = np.array([[1,2,3], [4,5,6], [7,8,9]])

matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
print(type(matriz))

<class 'numpy.ndarray'>


In [5]:
print(matriz.shape)

(3, 3)


In [8]:
# Criando uma matriz só com zeros
matriz_zeros = np.zeros((5, 5))

matriz_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# Criando uma matriz só com uns
matriz_ones = np.ones((5, 5))

matriz_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# A função matrix pega uma lista de lista e transforma em matriz

lista = [[1,2,3], [4,5,6]]

lista2 = np.matrix(lista)

print(type(lista2))


<class 'numpy.matrix'>


In [13]:
lista2.shape

(2, 3)

In [14]:
lista2.size

6

In [15]:
lista2.dtype

dtype('int32')

In [18]:
# Indexação em matrizes

index = np.matrix(([10,20,30], [40,50,60], [70,80,90]))

index


matrix([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

In [19]:
print(index[2,1])

80


In [20]:
print(index[0:2, 2])

[[30]
 [60]]


In [21]:
print(index[1,])

[[40 50 60]]


In [22]:
# Alterando um indice:
index[2, 1] = 100

print(index)

[[ 10  20  30]
 [ 40  50  60]
 [ 70 100  90]]


In [24]:
# Ao criar uma lista, eu posso forçar o tipo, ex:

vai_64 = np.array([1,2,3], dtype=np.float64)

print(vai_64.dtype)

float64


In [25]:
lista3 = np.array([[10,20,30], [40,50,60], [70,80,90]], dtype= float)

lista3.dtype

dtype('float64')

In [26]:
lista3.itemsize

8

In [27]:
lista3.nbytes

72

In [28]:
lista3.ndim

2

# Manipulando 3 e 4 dimensões

## 3D Array

In [29]:
mat3d = np.array([
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
            
        ],
        [
            [10,11,12],
            [13,14,15],
            [16,17,18]
        ]  
])


In [33]:
print(mat3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [34]:
print(mat3d.shape)

(2, 3, 3)


In [30]:
mat3d.ndim

3

In [31]:
mat3d.nbytes

72

In [32]:
mat3d.itemsize

4

In [ ]:
# Quero mudar o 14 por 140

In [35]:
mat3d[1,1,1] = 140

print(mat3d)

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 10  11  12]
  [ 13 140  15]
  [ 16  17  18]]]


In [36]:
# Quero exibir o numero 15
print(mat3d[1, 1, 2])

15


# Matriz com 4 dimensões



In [37]:
mat4d = np.array([
        [
            [
                [1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]
            ],
            [
                [10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]
            ],
            [
                [19, 20, 21],
                [22, 23, 24],
                [25, 26, 27]
            ]
            
        ],
        [
            [
                [28, 29, 30],
                [31, 32, 33],
                [34, 35, 36]
            ],
            [
                [37, 38, 39],
                [40, 41, 42],
                [43, 44, 45]
            ],
            [
                [46, 47, 48],
                [49, 50, 51],
                [52, 53, 54]
            ]
        ]  
])

In [44]:
print(mat4d)
print("-------")
print(mat4d.shape)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]]
-------
(2, 3, 3, 3)


In [45]:
# Quero troca o 32 por 320
mat4d[1, 0, 1, 1] = 320

print(mat4d)

[[[[  1   2   3]
   [  4   5   6]
   [  7   8   9]]

  [[ 10  11  12]
   [ 13  14  15]
   [ 16  17  18]]

  [[ 19  20  21]
   [ 22  23  24]
   [ 25  26  27]]]


 [[[ 28  29  30]
   [ 31 320  33]
   [ 34  35  36]]

  [[ 37  38  39]
   [ 40  41  42]
   [ 43  44  45]]

  [[ 46  47  48]
   [ 49  50  51]
   [ 52  53  54]]]]


In [39]:
mat4d.ndim

4

In [40]:
mat4d.itemsize

4

In [41]:
mat4d.nbytes

216

## Indexação 4D

In [47]:
# Quero exibir a linha completa
print(mat4d[0, 1, 2])

[16 17 18]
