## Iniciando o Numpy

In [1]:
# Importando o numpy
import numpy as np

In [19]:
# Criando uma lista com o numpy
array = np.array([1,2,3,4,5,6,7,8])
matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz3 = np.array([[[1],[2]], [[1], [2]], [[1], [2]]])

In [12]:
print(array, end='\n\n')
print(matriz, end='\n\n')
print(matriz3, end='\n\n')
# Um objeto ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
print(type(array))
print(type(matriz))
print(type(matriz3))


[1 2 3 4 5 6 7 8]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [20]:
# verificando o formato de dado: Repare que só tem uma única dimensão, ou seja, é um vetor
print(array.shape)
print(matriz.shape)
print(matriz3.shape)

(8,)
(3, 3)
(3, 2, 1)


## Indexação Numpy

In [21]:
print(array)

[1 2 3 4 5 6 7 8]


In [22]:
# Vamos pegar um valor especifico
print(array[4])

5


In [23]:
# Vamos pegar um intervalo
print(array[1:4])
print(array[1:4+1])

[2 3 4]
[2 3 4 5]


In [24]:
# Criando uma lista de indices
indices = [1, 4, 5, 0]
print(array[indices])

[2 5 6 1]


In [26]:
array2 = array
# Criando uma mascara booleana para filtrar os elementos pares
mask = (array2 % 2 == 0)
print(mask)
print(array2[mask])

[False  True False  True False  True False  True]
[2 4 6 8]


In [27]:
# Mudando um valor especifico
array2[0] = 999
print(array2)

[999   2   3   4   5   6   7   8]


### Atenção: Ao contrário de listas convencionais Python, o numpy não permite que eu mescle diferentes tipos de dados em um único array.