## Slicing - Fatiamento de arrays em Python

In [1]:
# Criando uma MATRIZ com valores na diagonal
import numpy as np

In [2]:
mat = np.diag(np.arange(3))

In [3]:
print(mat)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [4]:
mat[1,1]

1

In [5]:
# Exibindo toda a linha
mat[1]

array([0, 1, 0])

In [6]:
#Exibindo toda a coluna
mat[:,2]

array([0, 0, 2])

In [8]:
lista = np.arange(10)

lista

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# [start, end, step]
lista[2:9:3]

array([2, 5, 8])

In [12]:
a = np.array([1,2,2,4])
b = np.array([1,2,3,4])

In [13]:
# Comparo posições do array
a == b

array([ True,  True, False,  True])

In [14]:
# Comparação global do array
np.array_equal(a, b)

False

O método flatten() com NumPy é usado para criar uma cópia unidimensional (ou "achatada") de um array multidimensional. Isso significa que o método cria um novo array unidimensional, que contém todos os elementos do array multidimensional original, mas que está organizado em uma única linha. A ordem dos elementos no novo array unidimensional segue a ordem dos elementos no array multidimensional original.

In [15]:
mat2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
mat2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
mat2d.shape

(3, 3)

In [19]:
# Achatando a matriz
mat1d = mat2d.flatten()

In [20]:
mat1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
mat1d.shape

(9,)

#### Repetindo elementos de um array

In [22]:
lista2 = np.array([1,2,3])

lista2

array([1, 2, 3])

In [23]:
np.repeat(lista2, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [24]:
np.tile(lista2, 4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

### copiar um array

In [26]:
copia = np.copy(lista2)

copia

array([1, 2, 3])